# -*- coding: utf-8 -*-
"""gestion_fichiers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hzGe8dfXIQfl8EIVFTP9Nz3EuHMiQoAQ
"""

import numpy as np

# Ouvrir le fichier CSV en utilisant open()
with open('Loan_prediction_dataset.csv', 'r') as dataset:
    # Lire le contenu du fichier et stocker chaque ligne dans une liste
    bd =dataset.readlines()

# Créer une liste vide pour stocker les montants de prêt
loan_amounts = []

loan_amount = np.genfromtxt(bd, delimiter=',', usecols=(8,), dtype=float)

# Exclure les valeurs "nan" de la liste
loan_amount = loan_amount[~np.isnan(loan_amount)]

# Ajouter la valeur à la liste loan_amounts
loan_amounts.append(loan_amount)
print("LoanAmount:")
print(loan_amount)

# Calcul de la moyenne
moyenne_loan = np.mean(loan_amounts)
print(f"La moyenne des montants prêtés est : {moyenne_loan}")

# Calcul de la médiane
mediane_loan = np.median(loan_amounts)
print(f"Le montant médian des montants prêtés est : {mediane_loan}")

# Calcul de l'écart type
ecart_type = np.std(loan_amounts)
print(f"L'écart type des montants prêtés est : {ecart_type}")