# -*- coding: utf-8 -*-
"""gestion_fichiers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hzGe8dfXIQfl8EIVFTP9Nz3EuHMiQoAQ
"""

import numpy as np
from google.colab import files

# Charger le fichier CSV depuis votre ordinateur vers Colab
uploaded = files.upload()

# Spécifiez le chemin du fichier CSV
data_set = list(uploaded.keys())[0]  # Obtenir le nom du fichier téléchargé

# Charger les données depuis le fichier CSV en utilisant genfromtxt
loan_amount = np.genfromtxt(data_set, delimiter=',', skip_header=1, usecols=(8,), dtype=float)

# Exclure les valeurs "nan" de la liste
loan_amount = loan_amount[~np.isnan(loan_amount)]

# Affichez les valeurs de la 8e colonne après avoir exclu les "nan"
print(loan_amount)

# Calcul de la moyenne
moyenne_loan = np.mean(loan_amount)
print(f"La moyenne des montants prêtés est: {moyenne_loan}")

# Calcul de la médiane
mediane_loan = np.median(loan_amount)
print(f"Le montant médian des montants prêtés est : {mediane_loan}")

# Calcul de l'écart type
ecart_type = np.std(loan_amount)
print(f"L'écart type des montants prêtés est : {ecart_type}")